fix unit test failure in ./pkg/api/testing/serialization_test.go with error like:
    --- FAIL: TestSetControllerConversion (0.00s)
        serialization_test.go:104: rs._internal.apps -> rs.v1.apps
        serialization_test.go:107: unexpected encoding error: no kind "ReplicaSet" is registered for version "apps/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"

(cherry picked from commit 82f8f3e7d3ac2670e555bc372431a3f97349c6cb)